# Generated by Django 5.2 on 2025-04-23 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField()),
                ('altura_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_inicial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alergias', models.TextField(blank=True)),
                ('objetivo', models.CharField(max_length=200)),
                ('usuario', models.OneToOneField(help_text='Paciente ao qual esta ficha pertence', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
