# Generated by Django 5.2 on 2025-04-28 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='treinador',
            field=models.ForeignKey(blank=True, limit_choices_to={'perfil__tipo': 'educador_fisico'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercicios_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios_feitos', to=settings.AUTH_USER_MODEL),
        ),
    ]
