# Generated by Django 5.2 on 2025-04-23 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_anamnese'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('calorias', models.IntegerField(help_text='kcal por porção')),
                ('proteina_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carboidrato_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gordura_g', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('alimentos', models.ManyToManyField(help_text='Itens que compõem o cardápio', to='diario.alimento')),
                ('paciente', models.ForeignKey(help_text='Paciente que receberá este cardápio', limit_choices_to={'perfil__tipo': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
