# Generated by Django 5.2 on 2025-04-28 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_exercicio_treinador_alter_exercicio_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoProfissionalPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(limit_choices_to={'perfil__tipo': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_paciente', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(limit_choices_to={'perfil__tipo__in': ['nutricionista', 'educador_fisico']}, on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_profissional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo Profissional–Paciente',
                'verbose_name_plural': 'Vínculos Profissional–Paciente',
                'unique_together': {('profissional', 'paciente')},
            },
        ),
    ]
