# Generated by Django 5.2 on 2025-04-30 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_vinculoprofissionalpaciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('treinador', models.ForeignKey(limit_choices_to={'perfil__tipo': 'educador_fisico'}, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_educador_fisico', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(limit_choices_to={'perfil__tipo': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Alimento',
        ),
        migrations.RenameField(
            model_name='exercicio',
            old_name='tipo',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='duracao_minutos',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='treinador',
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes_feitas', to=settings.AUTH_USER_MODEL),
        ),
    ]
