# Generated by Django 5.2 on 2025-04-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0004_ficha_delete_alimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='nutricionista',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='treinador',
        ),
    ]
